import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Arbeit (Work) — 12 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/arbeit. Audio: Web Speech (de-DE).
 */
export const ARBEIT_LOS: LearningObject[] = [
  {
    id: 'lehrer',
    lemma: 'Lehrer',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'معلّم', en: 'teacher' },
    image: assetUrl('content/arbeit/lehrer.png'),
    imageKind: 'url',
    distractors: ['koch', 'polizist', 'bauer'],
  },
  {
    id: 'feuerwehrmann',
    lemma: 'Feuerwehrmann',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'رجل إطفاء', en: 'firefighter' },
    image: assetUrl('content/arbeit/feuerwehrmann.png'),
    imageKind: 'url',
    distractors: ['polizist', 'pilot', 'mechaniker'],
  },
  {
    id: 'polizist',
    lemma: 'Polizist',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'شرطي', en: 'police officer' },
    image: assetUrl('content/arbeit/polizist.png'),
    imageKind: 'url',
    distractors: ['feuerwehrmann', 'lehrer', 'brieftraeger'],
  },
  {
    id: 'koch',
    lemma: 'Koch',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'طبّاخ', en: 'cook' },
    image: assetUrl('content/arbeit/koch.png'),
    imageKind: 'url',
    distractors: ['baecker', 'bauer', 'friseur'],
  },
  {
    id: 'baecker',
    lemma: 'Bäcker',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'خبّاز', en: 'baker' },
    image: assetUrl('content/arbeit/baecker.png'),
    imageKind: 'url',
    distractors: ['koch', 'verkaeufer', 'bauer'],
  },
  {
    id: 'bauer',
    lemma: 'Bauer',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'مزارع', en: 'farmer' },
    image: assetUrl('content/arbeit/bauer.png'),
    imageKind: 'url',
    distractors: ['baecker', 'mechaniker', 'koch'],
  },
  {
    id: 'verkaeufer',
    lemma: 'Verkäufer',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'بائع', en: 'seller' },
    image: assetUrl('content/arbeit/verkaeufer.png'),
    imageKind: 'url',
    distractors: ['brieftraeger', 'lehrer', 'pilot'],
  },
  {
    id: 'pilot',
    lemma: 'Pilot',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'طيّار', en: 'pilot' },
    image: assetUrl('content/arbeit/pilot.png'),
    imageKind: 'url',
    distractors: ['brieftraeger', 'polizist', 'ingenieur'],
  },
  {
    id: 'ingenieur',
    lemma: 'Ingenieur',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'مهندس', en: 'engineer' },
    image: assetUrl('content/arbeit/ingenieur.png'),
    imageKind: 'url',
    distractors: ['mechaniker', 'pilot', 'lehrer'],
  },
  {
    id: 'brieftraeger',
    lemma: 'Briefträger',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'ساعي بريد', en: 'mail carrier' },
    image: assetUrl('content/arbeit/brieftraeger.png'),
    imageKind: 'url',
    distractors: ['verkaeufer', 'pilot', 'polizist'],
  },
  {
    id: 'mechaniker',
    lemma: 'Mechaniker',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'ميكانيكي', en: 'mechanic' },
    image: assetUrl('content/arbeit/mechaniker.png'),
    imageKind: 'url',
    distractors: ['ingenieur', 'bauer', 'koch'],
  },
  {
    id: 'friseur',
    lemma: 'Friseur',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'work',
    translations: { ar: 'حلاّق', en: 'hairdresser' },
    image: assetUrl('content/arbeit/friseur.png'),
    imageKind: 'url',
    distractors: ['koch', 'verkaeufer', 'lehrer'],
  },
];

export function getArbeitById(id: string): LearningObject | undefined {
  return ARBEIT_LOS.find((t) => t.id === id);
}

export function getArbeitPool(): LearningObject[] {
  return ARBEIT_LOS;
}
