/** Plural + example sentence overlays for Classic Cards (by LO id). */

export interface CardExtras {
  plural: string;
  example: string;
}

export const CARD_EXTRAS: Record<string, CardExtras> = {
  // Tiere
  katze: { plural: 'Katzen', example: 'Die Katze schläft.' },
  hund: { plural: 'Hunde', example: 'Der Hund bellt.' },
  fisch: { plural: 'Fische', example: 'Der Fisch schwimmt.' },
  vogel: { plural: 'Vögel', example: 'Der Vogel fliegt.' },
  pferd: { plural: 'Pferde', example: 'Das Pferd läuft schnell.' },
  kuh: { plural: 'Kühe', example: 'Die Kuh gibt Milch.' },
  schaf: { plural: 'Schafe', example: 'Das Schaf ist weiß.' },
  schwein: { plural: 'Schweine', example: 'Das Schwein ist rosa.' },
  hase: { plural: 'Hasen', example: 'Der Hase hoppelt.' },
  maus: { plural: 'Mäuse', example: 'Die Maus ist klein.' },
  elefant: { plural: 'Elefanten', example: 'Der Elefant ist groß.' },
  loewe: { plural: 'Löwen', example: 'Der Löwe brüllt.' },
  baer: { plural: 'Bären', example: 'Der Bär isst Honig.' },
  affe: { plural: 'Affen', example: 'Der Affe klettert.' },
  ente: { plural: 'Enten', example: 'Die Ente schwimmt.' },
  huhn: { plural: 'Hühner', example: 'Das Huhn legt Eier.' },
  frosch: { plural: 'Frösche', example: 'Der Frosch springt.' },
  schlange: { plural: 'Schlangen', example: 'Die Schlange kriecht.' },
  schildkroete: { plural: 'Schildkröten', example: 'Die Schildkröte ist langsam.' },
  biene: { plural: 'Bienen', example: 'Die Biene macht Honig.' },

  // Essen
  apfel: { plural: 'Äpfel', example: 'Der Apfel ist rot.' },
  banane: { plural: 'Bananen', example: 'Die Banane ist gelb.' },
  brot: { plural: 'Brote', example: 'Das Brot schmeckt gut.' },
  milch: { plural: '—', example: 'Die Milch ist kalt.' },
  kaese: { plural: 'Käse', example: 'Der Käse ist lecker.' },
  ei: { plural: 'Eier', example: 'Das Ei ist frisch.' },
  wasser: { plural: '—', example: 'Das Wasser ist klar.' },
  saft: { plural: 'Säfte', example: 'Der Saft ist süß.' },
  reis: { plural: '—', example: 'Der Reis ist heiß.' },
  nudeln: { plural: 'Nudeln', example: 'Die Nudeln sind lecker.' },
  suppe: { plural: 'Suppen', example: 'Die Suppe ist warm.' },
  salat: { plural: 'Salate', example: 'Der Salat ist frisch.' },
  tomate: { plural: 'Tomaten', example: 'Die Tomate ist rot.' },
  karotte: { plural: 'Karotten', example: 'Die Karotte ist orange.' },
  kartoffel: { plural: 'Kartoffeln', example: 'Die Kartoffel ist groß.' },
  eis: { plural: '—', example: 'Das Eis ist kalt.' },
  kuchen: { plural: 'Kuchen', example: 'Der Kuchen schmeckt süß.' },
  schokolade: { plural: 'Schokoladen', example: 'Die Schokolade ist süß.' },
  pizza: { plural: 'Pizzen', example: 'Die Pizza ist heiß.' },
  orange: { plural: 'Orangen', example: 'Die Orange ist saftig.' },

  // Farben (color nouns — plural often unused; orange extras live on LO to avoid Essen clash)
  rot: { plural: '—', example: 'Das Rot ist hell.' },
  blau: { plural: '—', example: 'Das Blau ist schön.' },
  gelb: { plural: '—', example: 'Das Gelb ist warm.' },
  gruen: { plural: '—', example: 'Das Grün ist frisch.' },
  rosa: { plural: '—', example: 'Das Rosa ist zart.' },
  lila: { plural: '—', example: 'Das Lila ist schön.' },
  braun: { plural: '—', example: 'Das Braun ist dunkel.' },
  grau: { plural: '—', example: 'Das Grau ist ruhig.' },
  schwarz: { plural: '—', example: 'Das Schwarz ist stark.' },
  weiss: { plural: '—', example: 'Das Weiß ist hell.' },

  // Familie (scaffolded — unlock when images land)
  mutter: { plural: 'Mütter', example: 'Die Mutter kocht.' },
  vater: { plural: 'Väter', example: 'Der Vater liest.' },
  kind: { plural: 'Kinder', example: 'Das Kind spielt.' },
  bruder: { plural: 'Brüder', example: 'Der Bruder lacht.' },
  schwester: { plural: 'Schwestern', example: 'Die Schwester singt.' },
  oma: { plural: 'Omas', example: 'Die Oma backt Kuchen.' },
  opa: { plural: 'Opas', example: 'Der Opa erzählt.' },
  baby: { plural: 'Babys', example: 'Das Baby schläft.' },
  familie: { plural: 'Familien', example: 'Die Familie isst zusammen.' },
  freund: { plural: 'Freunde', example: 'Der Freund kommt.' },
  freundin: { plural: 'Freundinnen', example: 'Die Freundin lacht.' },
  mann: { plural: 'Männer', example: 'Der Mann arbeitet.' },
  frau: { plural: 'Frauen', example: 'Die Frau liest.' },
  junge: { plural: 'Jungen', example: 'Der Junge spielt Fußball.' },
  maedchen: { plural: 'Mädchen', example: 'Das Mädchen malt.' },

  // Zuhause
  haus: { plural: 'Häuser', example: 'Das Haus ist groß.' },
  tuer: { plural: 'Türen', example: 'Die Tür ist offen.' },
  fenster: { plural: 'Fenster', example: 'Das Fenster ist hell.' },
  tisch: { plural: 'Tische', example: 'Der Tisch ist rund.' },
  stuhl: { plural: 'Stühle', example: 'Der Stuhl ist bequem.' },
  bett: { plural: 'Betten', example: 'Das Bett ist weich.' },
  lampe: { plural: 'Lampen', example: 'Die Lampe leuchtet.' },
  sofa: { plural: 'Sofas', example: 'Das Sofa ist gemütlich.' },
  kueche: { plural: 'Küchen', example: 'Die Küche ist hell.' },
  bad: { plural: 'Bäder', example: 'Das Bad ist sauber.' },
  schrank: { plural: 'Schränke', example: 'Der Schrank ist voll.' },
  schluessel: { plural: 'Schlüssel', example: 'Der Schlüssel öffnet die Tür.' },
  uhr: { plural: 'Uhren', example: 'Die Uhr zeigt die Zeit.' },
  spiegel: { plural: 'Spiegel', example: 'Der Spiegel ist klar.' },
  buch: { plural: 'Bücher', example: 'Das Buch ist interessant.' },
  tasse: { plural: 'Tassen', example: 'Die Tasse ist heiß.' },

  // Schule
  schule: { plural: 'Schulen', example: 'Die Schule ist groß.' },
  stift: { plural: 'Stifte', example: 'Der Stift schreibt gut.' },
  rucksack: { plural: 'Rucksäcke', example: 'Der Rucksack ist schwer.' },
  tafel: { plural: 'Tafeln', example: 'Die Tafel ist grün.' },
  schere: { plural: 'Scheren', example: 'Die Schere schneidet.' },
  lineal: { plural: 'Lineale', example: 'Das Lineal ist lang.' },
  globus: { plural: 'Globen', example: 'Der Globus zeigt die Welt.' },
  papier: { plural: '—', example: 'Das Papier ist weiß.' },
  lehrerin: { plural: 'Lehrerinnen', example: 'Die Lehrerin erklärt.' },
  schuelerin: { plural: 'Schülerinnen', example: 'Die Schülerin lernt.' },
  radierer: { plural: 'Radierer', example: 'Der Radierer löscht.' },
  pult: { plural: 'Pulte', example: 'Das Pult ist hoch.' },
  pause: { plural: 'Pausen', example: 'Die Pause ist kurz.' },


  // Kleidung
  tshirt: { plural: 'T-Shirts', example: 'Das T-Shirt ist blau.' },
  hose: { plural: 'Hosen', example: 'Die Hose ist neu.' },
  schuh: { plural: 'Schuhe', example: 'Der Schuh ist schwarz.' },
  jacke: { plural: 'Jacken', example: 'Die Jacke ist warm.' },
  muetze: { plural: 'Mützen', example: 'Die Mütze ist rot.' },
  kleid: { plural: 'Kleider', example: 'Das Kleid ist schön.' },
  socke: { plural: 'Socken', example: 'Die Socke ist weich.' },
  schal: { plural: 'Schals', example: 'Der Schal ist lang.' },
  handschuh: { plural: 'Handschuhe', example: 'Der Handschuh ist warm.' },
  rock: { plural: 'Röcke', example: 'Der Rock ist kurz.' },
  pullover: { plural: 'Pullover', example: 'Der Pullover ist weich.' },
  stiefel: { plural: 'Stiefel', example: 'Der Stiefel ist stark.' },
  schlafanzug: { plural: 'Schlafanzüge', example: 'Der Schlafanzug ist gemütlich.' },


  // Körper
  auge: { plural: 'Augen', example: 'Das Auge sieht gut.' },
  hand: { plural: 'Hände', example: 'Die Hand ist warm.' },
  fuss: { plural: 'Füße', example: 'Der Fuß ist groß.' },
  ohr: { plural: 'Ohren', example: 'Das Ohr hört gut.' },
  nase: { plural: 'Nasen', example: 'Die Nase ist klein.' },
  mund: { plural: 'Münder', example: 'Der Mund ist offen.' },
  kopf: { plural: 'Köpfe', example: 'Der Kopf ist rund.' },
  arm: { plural: 'Arme', example: 'Der Arm ist lang.' },
  bein: { plural: 'Beine', example: 'Das Bein ist stark.' },
  bauch: { plural: 'Bäuche', example: 'Der Bauch ist voll.' },
  finger: { plural: 'Finger', example: 'Der Finger ist dünn.' },
  zahn: { plural: 'Zähne', example: 'Der Zahn ist weiß.' },
  haar: { plural: 'Haare', example: 'Das Haar ist lang.' },
  herz: { plural: 'Herzen', example: 'Das Herz schlägt.' },


  // Wetter
  sonne: { plural: 'Sonnen', example: 'Die Sonne scheint.' },
  regen: { plural: '—', example: 'Der Regen fällt.' },
  schnee: { plural: '—', example: 'Der Schnee ist weiß.' },
  wind: { plural: 'Winde', example: 'Der Wind weht.' },
  gewitter: { plural: 'Gewitter', example: 'Das Gewitter ist laut.' },
  wolke: { plural: 'Wolken', example: 'Die Wolke ist grau.' },
  regenbogen: { plural: 'Regenbögen', example: 'Der Regenbogen ist bunt.' },
  nebel: { plural: '—', example: 'Der Nebel ist dicht.' },
  hitze: { plural: '—', example: 'Die Hitze ist stark.' },
  kaelte: { plural: '—', example: 'Die Kälte ist stark.' },
  mond: { plural: 'Monde', example: 'Der Mond ist hell.' },
  sturm: { plural: 'Stürme', example: 'Der Sturm ist stark.' },
  himmel: { plural: 'Himmel', example: 'Der Himmel ist blau.' },


  // Transport
  auto: { plural: 'Autos', example: 'Das Auto ist schnell.' },
  bus: { plural: 'Busse', example: 'Der Bus kommt.' },
  bahn: { plural: 'Bahnen', example: 'Die Bahn fährt ab.' },
  fahrrad: { plural: 'Fahrräder', example: 'Das Fahrrad ist grün.' },
  flugzeug: { plural: 'Flugzeuge', example: 'Das Flugzeug fliegt.' },
  schiff: { plural: 'Schiffe', example: 'Das Schiff schwimmt.' },
  taxi: { plural: 'Taxis', example: 'Das Taxi wartet.' },
  ubahn: { plural: 'U-Bahnen', example: 'Die U-Bahn ist schnell.' },
  strassenbahn: { plural: 'Straßenbahnen', example: 'Die Straßenbahn fährt.' },
  motorrad: { plural: 'Motorräder', example: 'Das Motorrad ist laut.' },
  lkw: { plural: 'LKWs', example: 'Der LKW ist groß.' },
  ampel: { plural: 'Ampeln', example: 'Die Ampel ist rot.' },

  // Natur
  baum: { plural: 'Bäume', example: 'Der Baum ist groß.' },
  blume: { plural: 'Blumen', example: 'Die Blume ist schön.' },
  blatt: { plural: 'Blätter', example: 'Das Blatt ist grün.' },
  berg: { plural: 'Berge', example: 'Der Berg ist hoch.' },
  see: { plural: 'Seen', example: 'Der See ist klar.' },
  fluss: { plural: 'Flüsse', example: 'Der Fluss ist lang.' },
  wald: { plural: 'Wälder', example: 'Der Wald ist grün.' },
  stein: { plural: 'Steine', example: 'Der Stein ist grau.' },
  stern: { plural: 'Sterne', example: 'Der Stern leuchtet.' },

  // Gesundheit
  arzt: { plural: 'Ärzte', example: 'Der Arzt hilft.' },
  krankenschwester: { plural: 'Krankenschwestern', example: 'Die Krankenschwester hilft.' },
  krankenhaus: { plural: 'Krankenhäuser', example: 'Das Krankenhaus ist groß.' },
  medizin: { plural: 'Medizin', example: 'Die Medizin hilft.' },
  apotheke: { plural: 'Apotheken', example: 'Die Apotheke ist offen.' },
  pflaster: { plural: 'Pflaster', example: 'Das Pflaster klebt.' },
  fieberthermometer: { plural: 'Fieberthermometer', example: 'Das Fieberthermometer zeigt die Temperatur.' },
  verband: { plural: 'Verbände', example: 'Der Verband ist sauber.' },
  impfung: { plural: 'Impfungen', example: 'Die Impfung schützt.' },
  tablette: { plural: 'Tabletten', example: 'Die Tablette ist klein.' },
  brille: { plural: 'Brillen', example: 'Die Brille ist neu.' },
  zahnarzt: { plural: 'Zahnärzte', example: 'Der Zahnarzt untersucht den Zahn.' },

  // Arbeit
  lehrer: { plural: 'Lehrer', example: 'Der Lehrer unterrichtet.' },
  feuerwehrmann: { plural: 'Feuerwehrmänner', example: 'Der Feuerwehrmann hilft.' },
  polizist: { plural: 'Polizisten', example: 'Der Polizist hilft.' },
  koch: { plural: 'Köche', example: 'Der Koch kocht.' },
  baecker: { plural: 'Bäcker', example: 'Der Bäcker backt Brot.' },
  bauer: { plural: 'Bauern', example: 'Der Bauer arbeitet.' },
  verkaeufer: { plural: 'Verkäufer', example: 'Der Verkäufer verkauft Brot.' },
  pilot: { plural: 'Piloten', example: 'Der Pilot fliegt.' },
  ingenieur: { plural: 'Ingenieure', example: 'Der Ingenieur plant.' },
  brieftraeger: { plural: 'Briefträger', example: 'Der Briefträger bringt Briefe.' },
  mechaniker: { plural: 'Mechaniker', example: 'Der Mechaniker repariert das Auto.' },
  friseur: { plural: 'Friseure', example: 'Der Friseur schneidet Haare.' },

  // Zahlen (number nouns — plural rare; examples use spoken counting forms)
  null: { plural: '—', example: 'Ich habe null Äpfel.' },
  eins: { plural: '—', example: 'Ich habe einen Apfel.' },
  zwei: { plural: '—', example: 'Ich habe zwei Äpfel.' },
  drei: { plural: '—', example: 'Ich sehe drei Katzen.' },
  vier: { plural: '—', example: 'Wir sind vier Freunde.' },
  fuenf: { plural: '—', example: 'Ich habe fünf Finger.' },
  sechs: { plural: '—', example: 'Der Würfel zeigt sechs.' },
  sieben: { plural: '—', example: 'Die Woche hat sieben Tage.' },
  acht: { plural: '—', example: 'Ich bin acht Jahre alt.' },
  neun: { plural: '—', example: 'Neun ist vor zehn.' },
  zehn: { plural: '—', example: 'Ich zähle bis zehn.' },
  elf: { plural: '—', example: 'Elf kommt nach zehn.' },
  zwoelf: { plural: '—', example: 'Die Uhr zeigt zwölf.' },

};

export function extrasFor(id: string): CardExtras {
  return CARD_EXTRAS[id] ?? { plural: '—', example: '' };
}
