import type { LearningObject } from './types';

/**
 * Level 1 · Essen (Food) — 20 Pre-A1 / A1 Learning Objects.
 * Images: generated painted PNGs served from /public/content/essen. Audio: Web Speech (de-DE).
 */
export const ESSEN_LOS: LearningObject[] = [
  {
    id: 'apfel',
    lemma: 'Apfel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'تفاحة', en: 'apple' },
    image: '/content/essen/apfel.png',
    imageKind: 'url',
    distractors: ['banane', 'orange', 'tomate'],
  },
  {
    id: 'banane',
    lemma: 'Banane',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'موزة', en: 'banana' },
    image: '/content/essen/banane.png',
    imageKind: 'url',
    distractors: ['apfel', 'orange', 'karotte'],
  },
  {
    id: 'brot',
    lemma: 'Brot',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'خبز', en: 'bread' },
    image: '/content/essen/brot.png',
    imageKind: 'url',
    distractors: ['kaese', 'kuchen', 'pizza'],
  },
  {
    id: 'milch',
    lemma: 'Milch',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'حليب', en: 'milk' },
    image: '/content/essen/milch.png',
    imageKind: 'url',
    distractors: ['wasser', 'saft', 'ei'],
  },
  {
    id: 'kaese',
    lemma: 'Käse',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'جبن', en: 'cheese' },
    image: '/content/essen/kaese.png',
    imageKind: 'url',
    distractors: ['brot', 'ei', 'salat'],
  },
  {
    id: 'ei',
    lemma: 'Ei',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'بيضة', en: 'egg' },
    image: '/content/essen/ei.png',
    imageKind: 'url',
    distractors: ['kaese', 'brot', 'milch'],
  },
  {
    id: 'wasser',
    lemma: 'Wasser',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'ماء', en: 'water' },
    image: '/content/essen/wasser.png',
    imageKind: 'url',
    distractors: ['saft', 'milch', 'suppe'],
  },
  {
    id: 'saft',
    lemma: 'Saft',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'عصير', en: 'juice' },
    image: '/content/essen/saft.png',
    imageKind: 'url',
    distractors: ['wasser', 'milch', 'orange'],
  },
  {
    id: 'reis',
    lemma: 'Reis',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'أرز', en: 'rice' },
    image: '/content/essen/reis.png',
    imageKind: 'url',
    distractors: ['nudeln', 'suppe', 'salat'],
  },
  {
    id: 'nudeln',
    lemma: 'Nudeln',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'معكرونة', en: 'noodles' },
    image: '/content/essen/nudeln.png',
    imageKind: 'url',
    distractors: ['reis', 'pizza', 'suppe'],
  },
  {
    id: 'suppe',
    lemma: 'Suppe',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'شوربة', en: 'soup' },
    image: '/content/essen/suppe.png',
    imageKind: 'url',
    distractors: ['salat', 'reis', 'nudeln'],
  },
  {
    id: 'salat',
    lemma: 'Salat',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'سلطة', en: 'salad' },
    image: '/content/essen/salat.png',
    imageKind: 'url',
    distractors: ['suppe', 'tomate', 'karotte'],
  },
  {
    id: 'tomate',
    lemma: 'Tomate',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'طماطم', en: 'tomato' },
    image: '/content/essen/tomate.png',
    imageKind: 'url',
    distractors: ['karotte', 'kartoffel', 'apfel'],
  },
  {
    id: 'karotte',
    lemma: 'Karotte',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'جزرة', en: 'carrot' },
    image: '/content/essen/karotte.png',
    imageKind: 'url',
    distractors: ['tomate', 'kartoffel', 'salat'],
  },
  {
    id: 'kartoffel',
    lemma: 'Kartoffel',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'بطاطا', en: 'potato' },
    image: '/content/essen/kartoffel.png',
    imageKind: 'url',
    distractors: ['karotte', 'tomate', 'brot'],
  },
  {
    id: 'eis',
    lemma: 'Eis',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'آيس كريم', en: 'ice cream' },
    image: '/content/essen/eis.png',
    imageKind: 'url',
    distractors: ['kuchen', 'schokolade', 'pizza'],
  },
  {
    id: 'kuchen',
    lemma: 'Kuchen',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'كعكة', en: 'cake' },
    image: '/content/essen/kuchen.png',
    imageKind: 'url',
    distractors: ['eis', 'schokolade', 'brot'],
  },
  {
    id: 'schokolade',
    lemma: 'Schokolade',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'شوكولاتة', en: 'chocolate' },
    image: '/content/essen/schokolade.png',
    imageKind: 'url',
    distractors: ['eis', 'kuchen', 'orange'],
  },
  {
    id: 'pizza',
    lemma: 'Pizza',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'بيتزا', en: 'pizza' },
    image: '/content/essen/pizza.png',
    imageKind: 'url',
    distractors: ['nudeln', 'brot', 'salat'],
  },
  {
    id: 'orange',
    lemma: 'Orange',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'food',
    translations: { ar: 'برتقالة', en: 'orange' },
    image: '/content/essen/orange.png',
    imageKind: 'url',
    distractors: ['apfel', 'banane', 'saft'],
  },
];

export function getEssenById(id: string): LearningObject | undefined {
  return ESSEN_LOS.find((t) => t.id === id);
}

export function getEssenPool(): LearningObject[] {
  return ESSEN_LOS;
}
