import type { LearningObject } from './types';

/**
 * Level 1 · Familie (Family) — 15 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/familie. Audio: Web Speech (de-DE).
 * Audio: Web Speech (de-DE).
 */
export const FAMILIE_LOS: LearningObject[] = [
  {
    id: 'mutter',
    lemma: 'Mutter',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'أم', en: 'mother' },
    image: '/content/familie/mutter.png',
    imageKind: 'url',
    distractors: ['vater', 'oma', 'frau'],
  },
  {
    id: 'vater',
    lemma: 'Vater',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'أب', en: 'father' },
    image: '/content/familie/vater.png',
    imageKind: 'url',
    distractors: ['mutter', 'opa', 'mann'],
  },
  {
    id: 'kind',
    lemma: 'Kind',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'طفل', en: 'child' },
    image: '/content/familie/kind.png',
    imageKind: 'url',
    distractors: ['baby', 'junge', 'maedchen'],
  },
  {
    id: 'bruder',
    lemma: 'Bruder',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'أخ', en: 'brother' },
    image: '/content/familie/bruder.png',
    imageKind: 'url',
    distractors: ['schwester', 'vater', 'junge'],
  },
  {
    id: 'schwester',
    lemma: 'Schwester',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'أخت', en: 'sister' },
    image: '/content/familie/schwester.png',
    imageKind: 'url',
    distractors: ['bruder', 'mutter', 'maedchen'],
  },
  {
    id: 'oma',
    lemma: 'Oma',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'جدة', en: 'grandma' },
    image: '/content/familie/oma.png',
    imageKind: 'url',
    distractors: ['opa', 'mutter', 'frau'],
  },
  {
    id: 'opa',
    lemma: 'Opa',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'جد', en: 'grandpa' },
    image: '/content/familie/opa.png',
    imageKind: 'url',
    distractors: ['oma', 'vater', 'mann'],
  },
  {
    id: 'baby',
    lemma: 'Baby',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'رضيع', en: 'baby' },
    image: '/content/familie/baby.png',
    imageKind: 'url',
    distractors: ['kind', 'junge', 'maedchen'],
  },
  {
    id: 'familie',
    lemma: 'Familie',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'عائلة', en: 'family' },
    image: '/content/familie/familie.png',
    imageKind: 'url',
    distractors: ['mutter', 'vater', 'kind'],
  },
  {
    id: 'freund',
    lemma: 'Freund',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'صديق', en: 'friend (m)' },
    image: '/content/familie/freund.png',
    imageKind: 'url',
    distractors: ['freundin', 'bruder', 'mann'],
  },
  {
    id: 'freundin',
    lemma: 'Freundin',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'صديقة', en: 'friend (f)' },
    image: '/content/familie/freundin.png',
    imageKind: 'url',
    distractors: ['freund', 'schwester', 'frau'],
  },
  {
    id: 'mann',
    lemma: 'Mann',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'رجل', en: 'man' },
    image: '/content/familie/mann.png',
    imageKind: 'url',
    distractors: ['frau', 'vater', 'opa'],
  },
  {
    id: 'frau',
    lemma: 'Frau',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'امرأة', en: 'woman' },
    image: '/content/familie/frau.png',
    imageKind: 'url',
    distractors: ['mann', 'mutter', 'oma'],
  },
  {
    id: 'junge',
    lemma: 'Junge',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'ولد', en: 'boy' },
    image: '/content/familie/junge.png',
    imageKind: 'url',
    distractors: ['maedchen', 'kind', 'bruder'],
  },
  {
    id: 'maedchen',
    lemma: 'Mädchen',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'family',
    translations: { ar: 'فتاة', en: 'girl' },
    image: '/content/familie/maedchen.png',
    imageKind: 'url',
    distractors: ['junge', 'kind', 'schwester'],
  },
];

export function getFamilieById(id: string): LearningObject | undefined {
  return FAMILIE_LOS.find((t) => t.id === id);
}

export function getFamiliePool(): LearningObject[] {
  return FAMILIE_LOS;
}
