import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Farben (Colors) — 11 Pre-A1 / A1 Learning Objects.
 * Color nouns use article "das". Images: /public/content/farben. Audio: Web Speech (de-DE).
 * Note: id "orange" overlaps Essen fruit id; LO-level plural/example win via enrich().
 */
export const FARBEN_LOS: LearningObject[] = [
  {
    id: 'rot',
    lemma: 'Rot',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أحمر', en: 'red' },
    image: assetUrl('content/farben/rot.png'),
    imageKind: 'url',
    distractors: ['blau', 'gelb', 'gruen'],
  },
  {
    id: 'blau',
    lemma: 'Blau',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أزرق', en: 'blue' },
    image: assetUrl('content/farben/blau.png'),
    imageKind: 'url',
    distractors: ['rot', 'gruen', 'gelb'],
  },
  {
    id: 'gelb',
    lemma: 'Gelb',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أصفر', en: 'yellow' },
    image: assetUrl('content/farben/gelb.png'),
    imageKind: 'url',
    distractors: ['rot', 'orange', 'gruen'],
  },
  {
    id: 'gruen',
    lemma: 'Grün',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أخضر', en: 'green' },
    image: assetUrl('content/farben/gruen.png'),
    imageKind: 'url',
    distractors: ['blau', 'gelb', 'braun'],
  },
  {
    id: 'orange',
    lemma: 'Orange',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'برتقالي', en: 'orange' },
    image: assetUrl('content/farben/orange.png'),
    imageKind: 'url',
    distractors: ['gelb', 'rot', 'rosa'],
    // Override Essen fruit extras (die Orange / Orangen)
    plural: '—',
    example: 'Das Orange ist warm.',
  },
  {
    id: 'rosa',
    lemma: 'Rosa',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'وردي', en: 'pink' },
    image: assetUrl('content/farben/rosa.png'),
    imageKind: 'url',
    distractors: ['lila', 'rot', 'weiss'],
  },
  {
    id: 'lila',
    lemma: 'Lila',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'بنفسجي', en: 'purple' },
    image: assetUrl('content/farben/lila.png'),
    imageKind: 'url',
    distractors: ['rosa', 'blau', 'rot'],
  },
  {
    id: 'braun',
    lemma: 'Braun',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'بني', en: 'brown' },
    image: assetUrl('content/farben/braun.png'),
    imageKind: 'url',
    distractors: ['grau', 'schwarz', 'gruen'],
  },
  {
    id: 'grau',
    lemma: 'Grau',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'رمادي', en: 'gray' },
    image: assetUrl('content/farben/grau.png'),
    imageKind: 'url',
    distractors: ['schwarz', 'weiss', 'braun'],
  },
  {
    id: 'schwarz',
    lemma: 'Schwarz',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أسود', en: 'black' },
    image: assetUrl('content/farben/schwarz.png'),
    imageKind: 'url',
    distractors: ['weiss', 'grau', 'braun'],
  },
  {
    id: 'weiss',
    lemma: 'Weiß',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'colors',
    translations: { ar: 'أبيض', en: 'white' },
    image: assetUrl('content/farben/weiss.png'),
    imageKind: 'url',
    distractors: ['schwarz', 'grau', 'rosa'],
  },
];

export function getFarbenById(id: string): LearningObject | undefined {
  return FARBEN_LOS.find((t) => t.id === id);
}

export function getFarbenPool(): LearningObject[] {
  return FARBEN_LOS;
}
