import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Gesundheit (Health) — 12 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/gesundheit. Audio: Web Speech (de-DE).
 */
export const GESUNDHEIT_LOS: LearningObject[] = [
  {
    id: 'arzt',
    lemma: 'Arzt',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'طبيب', en: 'doctor' },
    image: assetUrl('content/gesundheit/arzt.png'),
    imageKind: 'url',
    distractors: ['zahnarzt', 'krankenschwester', 'krankenhaus'],
  },
  {
    id: 'krankenschwester',
    lemma: 'Krankenschwester',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'ممرضة', en: 'nurse' },
    image: assetUrl('content/gesundheit/krankenschwester.png'),
    imageKind: 'url',
    distractors: ['arzt', 'zahnarzt', 'apotheke'],
  },
  {
    id: 'krankenhaus',
    lemma: 'Krankenhaus',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'مستشفى', en: 'hospital' },
    image: assetUrl('content/gesundheit/krankenhaus.png'),
    imageKind: 'url',
    distractors: ['arzt', 'krankenschwester', 'apotheke'],
  },
  {
    id: 'medizin',
    lemma: 'Medizin',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'دواء', en: 'medicine' },
    image: assetUrl('content/gesundheit/medizin.png'),
    imageKind: 'url',
    distractors: ['tablette', 'impfung', 'apotheke'],
  },
  {
    id: 'apotheke',
    lemma: 'Apotheke',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'صيدلية', en: 'pharmacy' },
    image: assetUrl('content/gesundheit/apotheke.png'),
    imageKind: 'url',
    distractors: ['medizin', 'tablette', 'verband'],
  },
  {
    id: 'pflaster',
    lemma: 'Pflaster',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'لاصقة طبية', en: 'plaster' },
    image: assetUrl('content/gesundheit/pflaster.png'),
    imageKind: 'url',
    distractors: ['verband', 'tablette', 'fieberthermometer'],
  },
  {
    id: 'fieberthermometer',
    lemma: 'Fieberthermometer',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'ميزان حرارة', en: 'thermometer' },
    image: assetUrl('content/gesundheit/fieberthermometer.png'),
    imageKind: 'url',
    distractors: ['pflaster', 'verband', 'impfung'],
  },
  {
    id: 'verband',
    lemma: 'Verband',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'ضمادة', en: 'bandage' },
    image: assetUrl('content/gesundheit/verband.png'),
    imageKind: 'url',
    distractors: ['pflaster', 'apotheke', 'medizin'],
  },
  {
    id: 'impfung',
    lemma: 'Impfung',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'تطعيم', en: 'vaccination' },
    image: assetUrl('content/gesundheit/impfung.png'),
    imageKind: 'url',
    distractors: ['medizin', 'tablette', 'fieberthermometer'],
  },
  {
    id: 'tablette',
    lemma: 'Tablette',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'حبة دواء', en: 'tablet' },
    image: assetUrl('content/gesundheit/tablette.png'),
    imageKind: 'url',
    distractors: ['medizin', 'apotheke', 'impfung'],
  },
  {
    id: 'brille',
    lemma: 'Brille',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'نظارة', en: 'glasses' },
    image: assetUrl('content/gesundheit/brille.png'),
    imageKind: 'url',
    distractors: ['arzt', 'zahnarzt', 'fieberthermometer'],
  },
  {
    id: 'zahnarzt',
    lemma: 'Zahnarzt',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'health',
    translations: { ar: 'طبيب أسنان', en: 'dentist' },
    image: assetUrl('content/gesundheit/zahnarzt.png'),
    imageKind: 'url',
    distractors: ['arzt', 'krankenhaus', 'brille'],
  },
];

export function getGesundheitById(id: string): LearningObject | undefined {
  return GESUNDHEIT_LOS.find((t) => t.id === id);
}

export function getGesundheitPool(): LearningObject[] {
  return GESUNDHEIT_LOS;
}
