import type { LearningObject } from './types';

/**
 * Level 1 · Kleidung (Clothes) — 13 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/kleidung. Audio: Web Speech (de-DE).
 */
export const KLEIDUNG_LOS: LearningObject[] = [
  {
    id: 'tshirt',
    lemma: 'T-Shirt',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'تي شيرت', en: 't-shirt' },
    image: '/content/kleidung/tshirt.png',
    imageKind: 'url',
    distractors: ['hose', 'pullover', 'jacke'],
  },
  {
    id: 'hose',
    lemma: 'Hose',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'بنطلون', en: 'pants' },
    image: '/content/kleidung/hose.png',
    imageKind: 'url',
    distractors: ['rock', 'schuh', 'tshirt'],
  },
  {
    id: 'schuh',
    lemma: 'Schuh',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'حذاء', en: 'shoe' },
    image: '/content/kleidung/schuh.png',
    imageKind: 'url',
    distractors: ['stiefel', 'socke', 'hose'],
  },
  {
    id: 'jacke',
    lemma: 'Jacke',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'سترة', en: 'jacket' },
    image: '/content/kleidung/jacke.png',
    imageKind: 'url',
    distractors: ['pullover', 'schal', 'tshirt'],
  },
  {
    id: 'muetze',
    lemma: 'Mütze',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'قبعة', en: 'hat/cap' },
    image: '/content/kleidung/muetze.png',
    imageKind: 'url',
    distractors: ['schal', 'handschuh', 'jacke'],
  },
  {
    id: 'kleid',
    lemma: 'Kleid',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'فستان', en: 'dress' },
    image: '/content/kleidung/kleid.png',
    imageKind: 'url',
    distractors: ['rock', 'hose', 'jacke'],
  },
  {
    id: 'socke',
    lemma: 'Socke',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'جورب', en: 'sock' },
    image: '/content/kleidung/socke.png',
    imageKind: 'url',
    distractors: ['schuh', 'stiefel', 'handschuh'],
  },
  {
    id: 'schal',
    lemma: 'Schal',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'وشاح', en: 'scarf' },
    image: '/content/kleidung/schal.png',
    imageKind: 'url',
    distractors: ['muetze', 'handschuh', 'jacke'],
  },
  {
    id: 'handschuh',
    lemma: 'Handschuh',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'قفاز', en: 'glove' },
    image: '/content/kleidung/handschuh.png',
    imageKind: 'url',
    distractors: ['schal', 'muetze', 'socke'],
  },
  {
    id: 'rock',
    lemma: 'Rock',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'تنورة', en: 'skirt' },
    image: '/content/kleidung/rock.png',
    imageKind: 'url',
    distractors: ['kleid', 'hose', 'tshirt'],
  },
  {
    id: 'pullover',
    lemma: 'Pullover',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'كنزة', en: 'sweater' },
    image: '/content/kleidung/pullover.png',
    imageKind: 'url',
    distractors: ['jacke', 'tshirt', 'schlafanzug'],
  },
  {
    id: 'stiefel',
    lemma: 'Stiefel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'حذاء طويل', en: 'boot' },
    image: '/content/kleidung/stiefel.png',
    imageKind: 'url',
    distractors: ['schuh', 'socke', 'hose'],
  },
  {
    id: 'schlafanzug',
    lemma: 'Schlafanzug',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'clothing',
    translations: { ar: 'بيجامة', en: 'pajamas' },
    image: '/content/kleidung/schlafanzug.png',
    imageKind: 'url',
    distractors: ['pullover', 'hose', 'tshirt'],
  },
];

export function getKleidungById(id: string): LearningObject | undefined {
  return KLEIDUNG_LOS.find((t) => t.id === id);
}

export function getKleidungPool(): LearningObject[] {
  return KLEIDUNG_LOS;
}
