import type { LearningObject } from './types';

/**
 * Level 1 · Körper (Body) — 14 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/koerper. Audio: Web Speech (de-DE).
 */
export const KOERPER_LOS: LearningObject[] = [
  {
    id: 'auge',
    lemma: 'Auge',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'عين', en: 'eye' },
    image: '/content/koerper/auge.png',
    imageKind: 'url',
    distractors: ['ohr', 'nase', 'mund'],
  },
  {
    id: 'hand',
    lemma: 'Hand',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'يد', en: 'hand' },
    image: '/content/koerper/hand.png',
    imageKind: 'url',
    distractors: ['finger', 'arm', 'fuss'],
  },
  {
    id: 'fuss',
    lemma: 'Fuß',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'قدم', en: 'foot' },
    image: '/content/koerper/fuss.png',
    imageKind: 'url',
    distractors: ['bein', 'hand', 'arm'],
  },
  {
    id: 'ohr',
    lemma: 'Ohr',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'أذن', en: 'ear' },
    image: '/content/koerper/ohr.png',
    imageKind: 'url',
    distractors: ['auge', 'nase', 'mund'],
  },
  {
    id: 'nase',
    lemma: 'Nase',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'أنف', en: 'nose' },
    image: '/content/koerper/nase.png',
    imageKind: 'url',
    distractors: ['mund', 'auge', 'ohr'],
  },
  {
    id: 'mund',
    lemma: 'Mund',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'فم', en: 'mouth' },
    image: '/content/koerper/mund.png',
    imageKind: 'url',
    distractors: ['nase', 'zahn', 'auge'],
  },
  {
    id: 'kopf',
    lemma: 'Kopf',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'رأس', en: 'head' },
    image: '/content/koerper/kopf.png',
    imageKind: 'url',
    distractors: ['haar', 'auge', 'ohr'],
  },
  {
    id: 'arm',
    lemma: 'Arm',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'ذراع', en: 'arm' },
    image: '/content/koerper/arm.png',
    imageKind: 'url',
    distractors: ['hand', 'bein', 'finger'],
  },
  {
    id: 'bein',
    lemma: 'Bein',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'ساق', en: 'leg' },
    image: '/content/koerper/bein.png',
    imageKind: 'url',
    distractors: ['fuss', 'arm', 'bauch'],
  },
  {
    id: 'bauch',
    lemma: 'Bauch',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'بطن', en: 'belly' },
    image: '/content/koerper/bauch.png',
    imageKind: 'url',
    distractors: ['herz', 'bein', 'kopf'],
  },
  {
    id: 'finger',
    lemma: 'Finger',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'إصبع', en: 'finger' },
    image: '/content/koerper/finger.png',
    imageKind: 'url',
    distractors: ['hand', 'arm', 'zahn'],
  },
  {
    id: 'zahn',
    lemma: 'Zahn',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'سن', en: 'tooth' },
    image: '/content/koerper/zahn.png',
    imageKind: 'url',
    distractors: ['mund', 'nase', 'auge'],
  },
  {
    id: 'haar',
    lemma: 'Haar',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'شعر', en: 'hair' },
    image: '/content/koerper/haar.png',
    imageKind: 'url',
    distractors: ['kopf', 'auge', 'ohr'],
  },
  {
    id: 'herz',
    lemma: 'Herz',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'body',
    translations: { ar: 'قلب', en: 'heart' },
    image: '/content/koerper/herz.png',
    imageKind: 'url',
    distractors: ['bauch', 'kopf', 'hand'],
  },
];

export function getKoerperById(id: string): LearningObject | undefined {
  return KOERPER_LOS.find((t) => t.id === id);
}

export function getKoerperPool(): LearningObject[] {
  return KOERPER_LOS;
}
