import type { LearningObject } from './types';

/**
 * Level 1 · Natur (Nature) — 12 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/natur. Audio: Web Speech (de-DE).
 */
export const NATUR_LOS: LearningObject[] = [
  {
    id: 'baum',
    lemma: 'Baum',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'شجرة', en: 'tree' },
    image: '/content/natur/baum.png',
    imageKind: 'url',
    distractors: ['blume', 'blatt', 'wald'],
  },
  {
    id: 'blume',
    lemma: 'Blume',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'زهرة', en: 'flower' },
    image: '/content/natur/blume.png',
    imageKind: 'url',
    distractors: ['baum', 'blatt', 'stein'],
  },
  {
    id: 'blatt',
    lemma: 'Blatt',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'ورقة', en: 'leaf' },
    image: '/content/natur/blatt.png',
    imageKind: 'url',
    distractors: ['blume', 'baum', 'stein'],
  },
  {
    id: 'sonne',
    lemma: 'Sonne',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'شمس', en: 'sun' },
    image: '/content/natur/sonne.png',
    imageKind: 'url',
    distractors: ['mond', 'stern', 'himmel'],
  },
  {
    id: 'mond',
    lemma: 'Mond',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'قمر', en: 'moon' },
    image: '/content/natur/mond.png',
    imageKind: 'url',
    distractors: ['sonne', 'stern', 'himmel'],
  },
  {
    id: 'stern',
    lemma: 'Stern',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'نجمة', en: 'star' },
    image: '/content/natur/stern.png',
    imageKind: 'url',
    distractors: ['mond', 'sonne', 'himmel'],
  },
  {
    id: 'berg',
    lemma: 'Berg',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'جبل', en: 'mountain' },
    image: '/content/natur/berg.png',
    imageKind: 'url',
    distractors: ['see', 'fluss', 'wald'],
  },
  {
    id: 'see',
    lemma: 'See',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'بحيرة', en: 'lake' },
    image: '/content/natur/see.png',
    imageKind: 'url',
    distractors: ['fluss', 'berg', 'wald'],
  },
  {
    id: 'fluss',
    lemma: 'Fluss',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'نهر', en: 'river' },
    image: '/content/natur/fluss.png',
    imageKind: 'url',
    distractors: ['see', 'berg', 'stein'],
  },
  {
    id: 'wald',
    lemma: 'Wald',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'غابة', en: 'forest' },
    image: '/content/natur/wald.png',
    imageKind: 'url',
    distractors: ['baum', 'berg', 'fluss'],
  },
  {
    id: 'stein',
    lemma: 'Stein',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'حجر', en: 'stone' },
    image: '/content/natur/stein.png',
    imageKind: 'url',
    distractors: ['berg', 'blatt', 'fluss'],
  },
  {
    id: 'himmel',
    lemma: 'Himmel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'nature',
    translations: { ar: 'سماء', en: 'sky' },
    image: '/content/natur/himmel.png',
    imageKind: 'url',
    distractors: ['sonne', 'mond', 'stern'],
  },
];

export function getNaturById(id: string): LearningObject | undefined {
  return NATUR_LOS.find((t) => t.id === id);
}

export function getNaturPool(): LearningObject[] {
  return NATUR_LOS;
}
