import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Schule (School) — 13 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/schule. Audio: Web Speech (de-DE).
 */
export const SCHULE_LOS: LearningObject[] = [
  {
    id: 'schule',
    lemma: 'Schule',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'مدرسة', en: 'school' },
    image: assetUrl('content/schule/schule.png'),
    imageKind: 'url',
    distractors: ['tafel', 'lehrerin', 'pause'],
  },
  {
    id: 'stift',
    lemma: 'Stift',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'قلم', en: 'pencil' },
    image: assetUrl('content/schule/stift.png'),
    imageKind: 'url',
    distractors: ['radierer', 'lineal', 'schere'],
  },
  {
    id: 'rucksack',
    lemma: 'Rucksack',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'حقيبة ظهر', en: 'backpack' },
    image: assetUrl('content/schule/rucksack.png'),
    imageKind: 'url',
    distractors: ['papier', 'stift', 'pult'],
  },
  {
    id: 'tafel',
    lemma: 'Tafel',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'سبورة', en: 'blackboard' },
    image: assetUrl('content/schule/tafel.png'),
    imageKind: 'url',
    distractors: ['pult', 'globus', 'schule'],
  },
  {
    id: 'schere',
    lemma: 'Schere',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'مقص', en: 'scissors' },
    image: assetUrl('content/schule/schere.png'),
    imageKind: 'url',
    distractors: ['stift', 'lineal', 'radierer'],
  },
  {
    id: 'lineal',
    lemma: 'Lineal',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'مسطرة', en: 'ruler' },
    image: assetUrl('content/schule/lineal.png'),
    imageKind: 'url',
    distractors: ['schere', 'stift', 'papier'],
  },
  {
    id: 'globus',
    lemma: 'Globus',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'كرة أرضية', en: 'globe' },
    image: assetUrl('content/schule/globus.png'),
    imageKind: 'url',
    distractors: ['tafel', 'pult', 'schule'],
  },
  {
    id: 'papier',
    lemma: 'Papier',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'ورق', en: 'paper' },
    image: assetUrl('content/schule/papier.png'),
    imageKind: 'url',
    distractors: ['stift', 'lineal', 'radierer'],
  },
  {
    id: 'lehrerin',
    lemma: 'Lehrerin',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'معلمة', en: 'teacher (f)' },
    image: assetUrl('content/schule/lehrerin.png'),
    imageKind: 'url',
    distractors: ['schuelerin', 'schule', 'pause'],
  },
  {
    id: 'schuelerin',
    lemma: 'Schülerin',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'تلميذة', en: 'student (f)' },
    image: assetUrl('content/schule/schuelerin.png'),
    imageKind: 'url',
    distractors: ['lehrerin', 'rucksack', 'pause'],
  },
  {
    id: 'radierer',
    lemma: 'Radierer',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'ممحاة', en: 'eraser' },
    image: assetUrl('content/schule/radierer.png'),
    imageKind: 'url',
    distractors: ['stift', 'schere', 'lineal'],
  },
  {
    id: 'pult',
    lemma: 'Pult',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'مكتب', en: 'desk' },
    image: assetUrl('content/schule/pult.png'),
    imageKind: 'url',
    distractors: ['tafel', 'globus', 'rucksack'],
  },
  {
    id: 'pause',
    lemma: 'Pause',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'school',
    translations: { ar: 'استراحة', en: 'recess/break' },
    image: assetUrl('content/schule/pause.png'),
    imageKind: 'url',
    distractors: ['schule', 'lehrerin', 'schuelerin'],
  },
];

export function getSchuleById(id: string): LearningObject | undefined {
  return SCHULE_LOS.find((t) => t.id === id);
}

export function getSchulePool(): LearningObject[] {
  return SCHULE_LOS;
}
