import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Tiere (Animals) — 20 Pre-A1 / A1 Learning Objects.
 * Images: generated painted PNGs served from /public/content/tiere. Audio: Web Speech (de-DE).
 */
export const TIERE_LOS: LearningObject[] = [
  {
    id: 'katze',
    lemma: 'Katze',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'قطة', en: 'cat' },
    image: assetUrl('content/tiere/katze.png'),
    imageKind: 'url',
    distractors: ['hund', 'maus', 'hase'],
  },
  {
    id: 'hund',
    lemma: 'Hund',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'كلب', en: 'dog' },
    image: assetUrl('content/tiere/hund.png'),
    imageKind: 'url',
    distractors: ['katze', 'schwein', 'baer'],
  },
  {
    id: 'fisch',
    lemma: 'Fisch',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'سمكة', en: 'fish' },
    image: assetUrl('content/tiere/fisch.png'),
    imageKind: 'url',
    distractors: ['vogel', 'frosch', 'ente'],
  },
  {
    id: 'vogel',
    lemma: 'Vogel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'طائر', en: 'bird' },
    image: assetUrl('content/tiere/vogel.png'),
    imageKind: 'url',
    distractors: ['fisch', 'biene', 'huhn'],
  },
  {
    id: 'pferd',
    lemma: 'Pferd',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'حصان', en: 'horse' },
    image: assetUrl('content/tiere/pferd.png'),
    imageKind: 'url',
    distractors: ['kuh', 'schaf', 'schwein'],
  },
  {
    id: 'kuh',
    lemma: 'Kuh',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'بقرة', en: 'cow' },
    image: assetUrl('content/tiere/kuh.png'),
    imageKind: 'url',
    distractors: ['pferd', 'schaf', 'schwein'],
  },
  {
    id: 'schaf',
    lemma: 'Schaf',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'خروف', en: 'sheep' },
    image: assetUrl('content/tiere/schaf.png'),
    imageKind: 'url',
    distractors: ['kuh', 'pferd', 'hase'],
  },
  {
    id: 'schwein',
    lemma: 'Schwein',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'خنزير', en: 'pig' },
    image: assetUrl('content/tiere/schwein.png'),
    imageKind: 'url',
    distractors: ['kuh', 'hund', 'pferd'],
  },
  {
    id: 'hase',
    lemma: 'Hase',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'أرنب', en: 'rabbit' },
    image: assetUrl('content/tiere/hase.png'),
    imageKind: 'url',
    distractors: ['maus', 'katze', 'schaf'],
  },
  {
    id: 'maus',
    lemma: 'Maus',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'فأر', en: 'mouse' },
    image: assetUrl('content/tiere/maus.png'),
    imageKind: 'url',
    distractors: ['hase', 'katze', 'frosch'],
  },
  {
    id: 'elefant',
    lemma: 'Elefant',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'فيل', en: 'elephant' },
    image: assetUrl('content/tiere/elefant.png'),
    imageKind: 'url',
    distractors: ['loewe', 'baer', 'affe'],
  },
  {
    id: 'loewe',
    lemma: 'Löwe',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'أسد', en: 'lion' },
    image: assetUrl('content/tiere/loewe.png'),
    imageKind: 'url',
    distractors: ['elefant', 'baer', 'affe'],
  },
  {
    id: 'baer',
    lemma: 'Bär',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'دب', en: 'bear' },
    image: assetUrl('content/tiere/baer.png'),
    imageKind: 'url',
    distractors: ['loewe', 'elefant', 'hund'],
  },
  {
    id: 'affe',
    lemma: 'Affe',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'قرد', en: 'monkey' },
    image: assetUrl('content/tiere/affe.png'),
    imageKind: 'url',
    distractors: ['elefant', 'loewe', 'baer'],
  },
  {
    id: 'ente',
    lemma: 'Ente',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'بطة', en: 'duck' },
    image: assetUrl('content/tiere/ente.png'),
    imageKind: 'url',
    distractors: ['huhn', 'vogel', 'fisch'],
  },
  {
    id: 'huhn',
    lemma: 'Huhn',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'دجاجة', en: 'chicken' },
    image: assetUrl('content/tiere/huhn.png'),
    imageKind: 'url',
    distractors: ['ente', 'vogel', 'biene'],
  },
  {
    id: 'frosch',
    lemma: 'Frosch',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'ضفدع', en: 'frog' },
    image: assetUrl('content/tiere/frosch.png'),
    imageKind: 'url',
    distractors: ['fisch', 'schlange', 'schildkroete'],
  },
  {
    id: 'schlange',
    lemma: 'Schlange',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'ثعبان', en: 'snake' },
    image: assetUrl('content/tiere/schlange.png'),
    imageKind: 'url',
    distractors: ['frosch', 'schildkroete', 'fisch'],
  },
  {
    id: 'schildkroete',
    lemma: 'Schildkröte',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'سلحفاة', en: 'turtle' },
    image: assetUrl('content/tiere/schildkroete.png'),
    imageKind: 'url',
    distractors: ['schlange', 'frosch', 'fisch'],
  },
  {
    id: 'biene',
    lemma: 'Biene',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'animals',
    translations: { ar: 'نحلة', en: 'bee' },
    image: assetUrl('content/tiere/biene.png'),
    imageKind: 'url',
    distractors: ['vogel', 'huhn', 'ente'],
  },
];

export function getTiereById(id: string): LearningObject | undefined {
  return TIERE_LOS.find((t) => t.id === id);
}

export function getTierePool(): LearningObject[] {
  return TIERE_LOS;
}
