import type { LearningObject } from './types';

/**
 * Level 1 · Transport (Verkehr) — 12 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/transport. Audio: Web Speech (de-DE).
 * Note: id `ubahn` (lemma U-Bahn); id `strassenbahn` (lemma Straßenbahn).
 */
export const TRANSPORT_LOS: LearningObject[] = [
  {
    id: 'auto',
    lemma: 'Auto',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'سيارة', en: 'car' },
    image: '/content/transport/auto.png',
    imageKind: 'url',
    distractors: ['bus', 'taxi', 'motorrad'],
  },
  {
    id: 'bus',
    lemma: 'Bus',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'حافلة', en: 'bus' },
    image: '/content/transport/bus.png',
    imageKind: 'url',
    distractors: ['bahn', 'strassenbahn', 'auto'],
  },
  {
    id: 'bahn',
    lemma: 'Bahn',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'قطار', en: 'train' },
    image: '/content/transport/bahn.png',
    imageKind: 'url',
    distractors: ['ubahn', 'strassenbahn', 'bus'],
  },
  {
    id: 'fahrrad',
    lemma: 'Fahrrad',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'دراجة', en: 'bicycle' },
    image: '/content/transport/fahrrad.png',
    imageKind: 'url',
    distractors: ['motorrad', 'auto', 'bus'],
  },
  {
    id: 'flugzeug',
    lemma: 'Flugzeug',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'طائرة', en: 'airplane' },
    image: '/content/transport/flugzeug.png',
    imageKind: 'url',
    distractors: ['schiff', 'bahn', 'bus'],
  },
  {
    id: 'schiff',
    lemma: 'Schiff',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'سفينة', en: 'ship' },
    image: '/content/transport/schiff.png',
    imageKind: 'url',
    distractors: ['flugzeug', 'bahn', 'bus'],
  },
  {
    id: 'taxi',
    lemma: 'Taxi',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'سيارة أجرة', en: 'taxi' },
    image: '/content/transport/taxi.png',
    imageKind: 'url',
    distractors: ['auto', 'bus', 'motorrad'],
  },
  {
    id: 'ubahn',
    lemma: 'U-Bahn',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'مترو', en: 'subway' },
    image: '/content/transport/ubahn.png',
    imageKind: 'url',
    distractors: ['bahn', 'strassenbahn', 'bus'],
  },
  {
    id: 'strassenbahn',
    lemma: 'Straßenbahn',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'ترام', en: 'tram' },
    image: '/content/transport/strassenbahn.png',
    imageKind: 'url',
    distractors: ['ubahn', 'bahn', 'bus'],
  },
  {
    id: 'motorrad',
    lemma: 'Motorrad',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'دراجة نارية', en: 'motorcycle' },
    image: '/content/transport/motorrad.png',
    imageKind: 'url',
    distractors: ['fahrrad', 'auto', 'bus'],
  },
  {
    id: 'lkw',
    lemma: 'LKW',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'شاحنة', en: 'truck' },
    image: '/content/transport/lkw.png',
    imageKind: 'url',
    distractors: ['bus', 'auto', 'bahn'],
  },
  {
    id: 'ampel',
    lemma: 'Ampel',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'transport',
    translations: { ar: 'إشارة مرور', en: 'traffic light' },
    image: '/content/transport/ampel.png',
    imageKind: 'url',
    distractors: ['auto', 'bus', 'fahrrad'],
  },
];

export function getTransportById(id: string): LearningObject | undefined {
  return TRANSPORT_LOS.find((t) => t.id === id);
}

export function getTransportPool(): LearningObject[] {
  return TRANSPORT_LOS;
}
