import type { LearningObject } from './types';

/**
 * Level 1 · Wetter (Weather) — 13 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/wetter. Audio: Web Speech (de-DE).
 */
export const WETTER_LOS: LearningObject[] = [
  {
    id: 'sonne',
    lemma: 'Sonne',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'شمس', en: 'sun' },
    image: '/content/wetter/sonne.png',
    imageKind: 'url',
    distractors: ['mond', 'himmel', 'wolke'],
  },
  {
    id: 'regen',
    lemma: 'Regen',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'مطر', en: 'rain' },
    image: '/content/wetter/regen.png',
    imageKind: 'url',
    distractors: ['schnee', 'wolke', 'regenbogen'],
  },
  {
    id: 'schnee',
    lemma: 'Schnee',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'ثلج', en: 'snow' },
    image: '/content/wetter/schnee.png',
    imageKind: 'url',
    distractors: ['regen', 'kaelte', 'wolke'],
  },
  {
    id: 'wind',
    lemma: 'Wind',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'ريح', en: 'wind' },
    image: '/content/wetter/wind.png',
    imageKind: 'url',
    distractors: ['sturm', 'wolke', 'himmel'],
  },
  {
    id: 'gewitter',
    lemma: 'Gewitter',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'عاصفة رعدية', en: 'thunderstorm' },
    image: '/content/wetter/gewitter.png',
    imageKind: 'url',
    distractors: ['sturm', 'regen', 'wolke'],
  },
  {
    id: 'wolke',
    lemma: 'Wolke',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'سحابة', en: 'cloud' },
    image: '/content/wetter/wolke.png',
    imageKind: 'url',
    distractors: ['himmel', 'regen', 'nebel'],
  },
  {
    id: 'regenbogen',
    lemma: 'Regenbogen',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'قوس قزح', en: 'rainbow' },
    image: '/content/wetter/regenbogen.png',
    imageKind: 'url',
    distractors: ['regen', 'sonne', 'wolke'],
  },
  {
    id: 'nebel',
    lemma: 'Nebel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'ضباب', en: 'fog' },
    image: '/content/wetter/nebel.png',
    imageKind: 'url',
    distractors: ['wolke', 'regen', 'kaelte'],
  },
  {
    id: 'hitze',
    lemma: 'Hitze',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'حرارة', en: 'heat' },
    image: '/content/wetter/hitze.png',
    imageKind: 'url',
    distractors: ['sonne', 'kaelte', 'himmel'],
  },
  {
    id: 'kaelte',
    lemma: 'Kälte',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'برد', en: 'cold' },
    image: '/content/wetter/kaelte.png',
    imageKind: 'url',
    distractors: ['schnee', 'hitze', 'wind'],
  },
  {
    id: 'mond',
    lemma: 'Mond',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'قمر', en: 'moon' },
    image: '/content/wetter/mond.png',
    imageKind: 'url',
    distractors: ['sonne', 'himmel', 'wolke'],
  },
  {
    id: 'sturm',
    lemma: 'Sturm',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'عاصفة', en: 'storm' },
    image: '/content/wetter/sturm.png',
    imageKind: 'url',
    distractors: ['wind', 'gewitter', 'regen'],
  },
  {
    id: 'himmel',
    lemma: 'Himmel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'weather',
    translations: { ar: 'سماء', en: 'sky' },
    image: '/content/wetter/himmel.png',
    imageKind: 'url',
    distractors: ['wolke', 'sonne', 'mond'],
  },
];

export function getWetterById(id: string): LearningObject | undefined {
  return WETTER_LOS.find((t) => t.id === id);
}

export function getWetterPool(): LearningObject[] {
  return WETTER_LOS;
}
