import type { LearningObject } from './types';

/**
 * Level 1 · Zahlen (Numbers 0–12) — 13 Pre-A1 / A1 Learning Objects.
 * Number nouns use article "die" (die Eins, die Zwei…). Lemmas capitalized like Farben.
 * Spoken counting forms appear in example sentences (zwei Äpfel…).
 * Images: /public/content/zahlen. Audio: Web Speech (de-DE).
 */
export const ZAHLEN_LOS: LearningObject[] = [
  {
    id: 'null',
    lemma: 'Null',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'صفر', en: 'zero' },
    image: '/content/zahlen/null.png',
    imageKind: 'url',
    distractors: ['eins', 'zwei', 'zehn'],
  },
  {
    id: 'eins',
    lemma: 'Eins',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'واحد', en: 'one' },
    image: '/content/zahlen/eins.png',
    imageKind: 'url',
    distractors: ['null', 'zwei', 'drei'],
  },
  {
    id: 'zwei',
    lemma: 'Zwei',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'اثنان', en: 'two' },
    image: '/content/zahlen/zwei.png',
    imageKind: 'url',
    distractors: ['eins', 'drei', 'vier'],
  },
  {
    id: 'drei',
    lemma: 'Drei',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'ثلاثة', en: 'three' },
    image: '/content/zahlen/drei.png',
    imageKind: 'url',
    distractors: ['zwei', 'vier', 'fuenf'],
  },
  {
    id: 'vier',
    lemma: 'Vier',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'أربعة', en: 'four' },
    image: '/content/zahlen/vier.png',
    imageKind: 'url',
    distractors: ['drei', 'fuenf', 'sechs'],
  },
  {
    id: 'fuenf',
    lemma: 'Fünf',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'خمسة', en: 'five' },
    image: '/content/zahlen/fuenf.png',
    imageKind: 'url',
    distractors: ['vier', 'sechs', 'sieben'],
  },
  {
    id: 'sechs',
    lemma: 'Sechs',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'ستة', en: 'six' },
    image: '/content/zahlen/sechs.png',
    imageKind: 'url',
    distractors: ['fuenf', 'sieben', 'acht'],
  },
  {
    id: 'sieben',
    lemma: 'Sieben',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'سبعة', en: 'seven' },
    image: '/content/zahlen/sieben.png',
    imageKind: 'url',
    distractors: ['sechs', 'acht', 'neun'],
  },
  {
    id: 'acht',
    lemma: 'Acht',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'ثمانية', en: 'eight' },
    image: '/content/zahlen/acht.png',
    imageKind: 'url',
    distractors: ['sieben', 'neun', 'zehn'],
  },
  {
    id: 'neun',
    lemma: 'Neun',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'تسعة', en: 'nine' },
    image: '/content/zahlen/neun.png',
    imageKind: 'url',
    distractors: ['acht', 'zehn', 'elf'],
  },
  {
    id: 'zehn',
    lemma: 'Zehn',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'عشرة', en: 'ten' },
    image: '/content/zahlen/zehn.png',
    imageKind: 'url',
    distractors: ['neun', 'elf', 'zwoelf'],
  },
  {
    id: 'elf',
    lemma: 'Elf',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'أحد عشر', en: 'eleven' },
    image: '/content/zahlen/elf.png',
    imageKind: 'url',
    distractors: ['zehn', 'zwoelf', 'neun'],
  },
  {
    id: 'zwoelf',
    lemma: 'Zwölf',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'numbers',
    translations: { ar: 'اثنا عشر', en: 'twelve' },
    image: '/content/zahlen/zwoelf.png',
    imageKind: 'url',
    distractors: ['elf', 'zehn', 'null'],
  },
];

export function getZahlenById(id: string): LearningObject | undefined {
  return ZAHLEN_LOS.find((t) => t.id === id);
}

export function getZahlenPool(): LearningObject[] {
  return ZAHLEN_LOS;
}
