import type { LearningObject } from './types';
import { assetUrl } from './assetUrl';

/**
 * Level 1 · Zuhause (Home) — 16 Pre-A1 / A1 Learning Objects.
 * Images: /public/content/zuhause. Audio: Web Speech (de-DE).
 */
export const ZUHAUSE_LOS: LearningObject[] = [
  {
    id: 'haus',
    lemma: 'Haus',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'منزل', en: 'house' },
    image: assetUrl('content/zuhause/haus.png'),
    imageKind: 'url',
    distractors: ['tuer', 'fenster', 'kueche'],
  },
  {
    id: 'tuer',
    lemma: 'Tür',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'باب', en: 'door' },
    image: assetUrl('content/zuhause/tuer.png'),
    imageKind: 'url',
    distractors: ['fenster', 'haus', 'schrank'],
  },
  {
    id: 'fenster',
    lemma: 'Fenster',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'نافذة', en: 'window' },
    image: assetUrl('content/zuhause/fenster.png'),
    imageKind: 'url',
    distractors: ['tuer', 'haus', 'spiegel'],
  },
  {
    id: 'tisch',
    lemma: 'Tisch',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'طاولة', en: 'table' },
    image: assetUrl('content/zuhause/tisch.png'),
    imageKind: 'url',
    distractors: ['stuhl', 'sofa', 'schrank'],
  },
  {
    id: 'stuhl',
    lemma: 'Stuhl',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'كرسي', en: 'chair' },
    image: assetUrl('content/zuhause/stuhl.png'),
    imageKind: 'url',
    distractors: ['tisch', 'sofa', 'bett'],
  },
  {
    id: 'bett',
    lemma: 'Bett',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'سرير', en: 'bed' },
    image: assetUrl('content/zuhause/bett.png'),
    imageKind: 'url',
    distractors: ['sofa', 'stuhl', 'schrank'],
  },
  {
    id: 'lampe',
    lemma: 'Lampe',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'مصباح', en: 'lamp' },
    image: assetUrl('content/zuhause/lampe.png'),
    imageKind: 'url',
    distractors: ['uhr', 'spiegel', 'tasse'],
  },
  {
    id: 'sofa',
    lemma: 'Sofa',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'أريكة', en: 'sofa' },
    image: assetUrl('content/zuhause/sofa.png'),
    imageKind: 'url',
    distractors: ['bett', 'stuhl', 'tisch'],
  },
  {
    id: 'kueche',
    lemma: 'Küche',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'مطبخ', en: 'kitchen' },
    image: assetUrl('content/zuhause/kueche.png'),
    imageKind: 'url',
    distractors: ['bad', 'haus', 'tisch'],
  },
  {
    id: 'bad',
    lemma: 'Bad',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'حمّام', en: 'bathroom' },
    image: assetUrl('content/zuhause/bad.png'),
    imageKind: 'url',
    distractors: ['kueche', 'spiegel', 'haus'],
  },
  {
    id: 'schrank',
    lemma: 'Schrank',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'خزانة', en: 'wardrobe' },
    image: assetUrl('content/zuhause/schrank.png'),
    imageKind: 'url',
    distractors: ['tisch', 'bett', 'sofa'],
  },
  {
    id: 'schluessel',
    lemma: 'Schlüssel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'مفتاح', en: 'key' },
    image: assetUrl('content/zuhause/schluessel.png'),
    imageKind: 'url',
    distractors: ['tuer', 'uhr', 'buch'],
  },
  {
    id: 'uhr',
    lemma: 'Uhr',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'ساعة', en: 'clock' },
    image: assetUrl('content/zuhause/uhr.png'),
    imageKind: 'url',
    distractors: ['lampe', 'spiegel', 'schluessel'],
  },
  {
    id: 'spiegel',
    lemma: 'Spiegel',
    article: 'der',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'مرآة', en: 'mirror' },
    image: assetUrl('content/zuhause/spiegel.png'),
    imageKind: 'url',
    distractors: ['fenster', 'uhr', 'bad'],
  },
  {
    id: 'buch',
    lemma: 'Buch',
    article: 'das',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'كتاب', en: 'book' },
    image: assetUrl('content/zuhause/buch.png'),
    imageKind: 'url',
    distractors: ['tasse', 'lampe', 'schluessel'],
  },
  {
    id: 'tasse',
    lemma: 'Tasse',
    article: 'die',
    language: 'de',
    cefr: 'pre',
    difficulty: 1,
    category: 'home',
    translations: { ar: 'كوب', en: 'cup' },
    image: assetUrl('content/zuhause/tasse.png'),
    imageKind: 'url',
    distractors: ['buch', 'lampe', 'tisch'],
  },
];

export function getZuhauseById(id: string): LearningObject | undefined {
  return ZUHAUSE_LOS.find((t) => t.id === id);
}

export function getZuhausePool(): LearningObject[] {
  return ZUHAUSE_LOS;
}
